sonar.projectKey=Current-Calendar_app
sonar.organization=current-calendar


sonar.sources=backend

sonar.exclusions=**/node_modules/**, **/.expo/**, **/migrations/**, **/venv/**, **/htmlcov/**, backend/manage.py, **/consumers.py, **/middleware.py, **/routing.py, **/main/management/commands/**, **/utils/security.py, **/asgi.py, **/wsgi.py, backend/scripts/**

sonar.test.inclusions=backend/**/tests/**, backend/**/tests.py, backend/**/test_*.py


sonar.python.coverage.reportPaths=backend/coverage.xml

# sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
