sonar.projectKey=current
sonar.projectName=Current

sonar.sources=backend,frontend

sonar.exclusions=**/node_modules/**, **/venv/**, **/env/**, **/__pycache__/**, **/migrations/**, **/.expo/**, **/ios/**, **/android/**, **/.bundle/**

sonar.host.url=http://sonarqube:9000