# Generated by Django 5.2.11 on 2026-03-18 11:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=main.models.calendar_cover_path),
        ),
    ]
