# Generated by Django 5.2.11 on 2026-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_eventattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_attendance'),
        ),
    ]
