# Generated by Django 5.2.11 on 2026-03-17 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_calendar_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=2000)),
                ("replies_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "calendar",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="main.calendar"),
                ),
                (
                    "event",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="main.event"),
                ),
                (
                    "parent",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="main.comment"),
                ),
                (
                    "root",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thread_comments", to="main.comment"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event", "-created_at", "-id"], name="comment_event_feed_idx"),
                    models.Index(fields=["calendar", "-created_at", "-id"], name="comment_calendar_feed_idx"),
                    models.Index(fields=["root", "created_at", "id"], name="comment_root_thread_idx"),
                    models.Index(fields=["parent", "created_at", "id"], name="comment_parent_thread_idx"),
                    models.Index(fields=["author", "-created_at", "-id"], name="comment_author_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(calendar__isnull=True, event__isnull=False)
                    | models.Q(calendar__isnull=False, event__isnull=True)
                ),
                name="comment_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(condition=~models.Q(parent=models.F("id")), name="comment_parent_not_self"),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=~models.Q(root=models.F("id")) | models.Q(parent__isnull=True),
                name="comment_root_self_only_for_roots",
            ),
        ),
    ]
