# Generated by Django 5.2.11 on 2026-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_threads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarlike',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='calendarlike',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_exactly_one_target',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', False), ('calendar__isnull', True)), models.Q(('event__isnull', True), ('calendar__isnull', False)), _connector='OR'), name='comment_exactly_one_target'),
        ),
        migrations.DeleteModel(
            name='CalendarLike',
        ),
    ]
