# Generated by Django 5.2.11 on 2026-03-20 22:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_calendarlike_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CalendarLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'calendar'), name='unique_calendar_like_per_user')],
            },
        ),
    ]
