# Generated by Django 5.2.11 on 2026-03-22 01:08

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_calendar_likes_count_calendarlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.calendar_cover_path),
        ),
    ]
