# Generated by Django 5.2.11 on 2026-03-22 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_calendar_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='co_owners',
            field=models.ManyToManyField(blank=True, related_name='co_owned_calendars', to=settings.AUTH_USER_MODEL),
        ),
    ]
