# Generated by Django 5.2.11 on 2026-03-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_notification_type'),
        ('main', '0013_chatmessage'),
    ]

    operations = [
    ]
