# Generated by Django 5.2.11 on 2026-03-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_calendar_co_owners'),
        ('main', '0014_merge_0013_alter_notification_type_0013_chatmessage'),
    ]

    operations = [
    ]
