# Generated by Django 5.2.11 on 2026-03-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification'),
        ('main', '0015_merge_20260324_0123'),
    ]

    operations = [
    ]
