# Generated by Django 5.2.11 on 2026-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20260324_1552'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('privacy', 'PRIVATE')), fields=('creator',), name='unique_private_calendar_per_user'),
        ),
    ]
