# Generated by Django 5.2.11 on 2026-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_calendar_unique_private_calendar_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('BUSINESS', 'Business')], default='FREE', max_length=20),
        ),
    ]
