# Generated by Django 5.2.11 on 2026-04-07 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CalendarInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit')], default='VIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=None, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='main.calendar')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_calendar_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_calendar_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
