# Generated by Django 5.2.11 on 2026-04-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_calendar_viewers_calendarinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_FOLLOWER', 'New Follower'), ('CALENDAR_FOLLOW', 'Calendar Follow'), ('EVENT_SAVED', 'Event Saved'), ('EVENT_LIKED', 'Event Liked'), ('EVENT_COMMENT', 'Event Comment'), ('CALENDAR_COMMENT', 'Calendar Comment'), ('EVENT_INVITE', 'Event Invite'), ('CALENDAR_INVITE', 'Calendar Invite')], max_length=20),
        ),
    ]
