# Generated by Django 5.2.11 on 2026-04-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_category_and_eventtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='eventtag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='eventtag',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_tag_per_category'),
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='updated_at',
        ),
    ]
