import { StyleSheet } from "react-native";

const TEAL = "#1F6A6A";
const TEAL_DARK = "#0F4E4F";
const TEXT = "#10464D";
const BOTTOM_BAR_HEIGHT = 64;

export const styles = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: BOTTOM_BAR_HEIGHT + 12,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 999,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 16,
    shadowColor: TEAL_DARK,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
    borderWidth: 1.5,
    borderColor: "rgba(31,106,106,0.12)",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: TEAL,
    justifyContent: "center",
    alignItems: "center",
  },
  stepBadge: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "rgba(31,106,106,0.08)",
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  stepText: { fontSize: 11, fontWeight: "700", color: TEAL, letterSpacing: 0.5 },
  closeBtn: { padding: 4 },
  dots: { flexDirection: "row", gap: 5, marginBottom: 12 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "rgba(31,106,106,0.2)" },
  dotActive: { width: 18, backgroundColor: TEAL },
  title: { fontSize: 17, fontWeight: "800", color: TEXT, marginBottom: 6 },
  description: { fontSize: 13, color: TEXT, opacity: 0.75, lineHeight: 19, marginBottom: 16 },
  buttons: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  btnPrimary: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: TEAL,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    borderWidth: 1.5,
    borderColor: TEAL_DARK,
    shadowColor: TEAL_DARK,
    shadowOpacity: 0.18,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  btnPrimaryText: { color: "#EAF7F6", fontWeight: "800", fontSize: 13 },
  btnSecondary: {
    flex: 0.5,
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
    borderWidth: 1.5,
    borderColor: "rgba(31,106,106,0.25)",
  },
  btnSecondaryText: { color: TEAL, fontWeight: "700", fontSize: 13 },
  btnDisabled: { borderColor: "#e0e0e0" },
  welcomeOverlay: {
    flex: 1,
    backgroundColor: "rgba(10, 40, 40, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  welcomeCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 28,
    alignItems: "center",
    shadowColor: TEAL_DARK,
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
    overflow: "hidden",
    position: "relative",
  },
  welcomeBubbles: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  welcomeBubble: {
    position: "absolute",
    borderRadius: 999,
  },
  welcomeIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 18,
    backgroundColor: TEAL,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
  },
  welcomeTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: TEXT,
    marginBottom: 8,
    textAlign: "center",
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: TEXT,
    opacity: 0.8,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 18,
  },
  welcomeFeatureList: {
    width: "100%",
    gap: 12,
    marginBottom: 20,
  },
  welcomeFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  welcomeFeatureText: {
    color: TEXT,
    fontSize: 14,
    fontWeight: "600",
  },
  welcomeBtnPrimary: {
    width: "100%",
    backgroundColor: TEAL,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: TEAL_DARK,
    marginBottom: 10,
  },
  welcomeBtnPrimaryText: {
    color: "#EAF7F6",
    fontWeight: "800",
    fontSize: 15,
  },
  welcomeBtnSecondary: {
    width: "100%",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(31,106,106,0.18)",
  },
  welcomeBtnSecondaryText: {
    color: TEAL,
    fontWeight: "700",
    fontSize: 13,
  },
});